# Generated by Django 5.0.7 on 2024-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_formname_delete_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formname',
            name='image',
            field=models.ImageField(upload_to='form'),
        ),
    ]
